### ISSUE TITLE
vaadin project base starter pack does not work

### ISSUE THREAD

**Issue by dumischbaenger** [devsoap/gradle-vaadin-flow#116]
I'm a vaadin beginner and downloaded last week the projekt base starter pack and adapted it to gradle.

This week I read of the official gradle support. I tried to adapt my gradle.build to the vaadin plugin. 

This worked apart from one thing. If I replace
`compile "com.vaadin:vaadin-core:10.0.4"`
with
`implementation vaadin.core()`
I can start jetty but in the logs the entry
`[main] INFO com.vaadin.flow.server.startup.ServletDeployer - Automatically deploying Vaadin servlet to /*`
is missing and in the browser the directory is listet instead of starting the app.

My build.gradle:
```
plugins {
  id "org.akhikhl.gretty" version "2.0.0"
  id 'com.devsoap.vaadin-flow' version '1.0.0.M4.1'
  id "eclipse" 
  id "groovy" 
  id "war" 
}

vaadin.version="10.0.4"


repositories { 
  jcenter()
  vaadin.repositories()
}

dependencies {
  compile 'org.codehaus.groovy:groovy-all:2.4.13'
  implementation vaadin.bom()
  implementation vaadin.core()

  
  //compile "com.vaadin:vaadin-core:10.0.4"
  compile "org.slf4j:slf4j-simple:1.7.25"
}
```

The project consists of only one file MainView.java:
```
package de.dumischbaenger;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

/**
 * The main view contains a button and a click listener.
 */
@Route
public class MainView extends VerticalLayout {

    public MainView() {
        Button button = new Button("Click me",
                event -> Notification.show("Clicked!"));
        add(button);
    }   
}

```

**Comment by johndevs** [comment]
Hi, 

I think you are almost there. Just a few things missing:


> ``id 'com.devsoap.vaadin-flow' version '1.0.0.M4.1'``

Use the latest plugin instead so replace this with ``id 'com.devsoap.vaadin-flow' version '1.0.0.M5'``

>If I replace ``compile "com.vaadin:vaadin-core:10.0.4"`` with``implementation vaadin.core()``
> I can start jetty but [...] in the browser the directory is listed instead of starting the app.

The Gretty plugin does not currently support having the dependencies in ``implementation``. You can replace that with ``compile vaadin.core()``.

> ``compile 'org.codehaus.groovy:groovy-all:2.4.13'``

This can be replaced with ``compile vaadin.groovy()``

> ``//compile "com.vaadin:vaadin-core:10.0.4"``

This can be removed as you are already doing this with ``compile vaadin.core()``

>`` compile "org.slf4j:slf4j-simple:1.7.25"``

This can be replaced with ``compile vaadin.slf4j()``

After you've done that it should work.

If you want an example of porting the starter to Gradle I already did that for the Beverage starter a while ago, the project can be found here https://github.com/devsoap/examples/tree/master/beverage-starter-flow-gradle. Maybe you can compare that to your own and see the differences.
