### ISSUE TITLE
Require Gradle 5

### ISSUE THREAD

**Issue by johndevs** [devsoap/gradle-vaadin-flow#126]
The final stable plugin version should be based on the upcoming Gradle 5 series to be forward compatible without breaking changes as long as possible.

**Comment by bsideup** [comment]
@johndevs just FYI this change is a bummer for us and we consider forking the plugin just to continue using it with Gradle 4.x (latest release) 🤔

**Comment by johndevs** [comment]
@bsideup I understand it will be an issue right now until the first Gradle 5 stable release is made but there is a good reason for this.

The Vaadin platform is investing heavily in building their dependencies based on BOM (Maven Bill Of Materials) and Gradle 4.x has *some* support for them (enabled by using the preview setting), but it is not complete. 

The Gradle team re-wrote the BOM support in Gradle 5 to fully support the specification and it is not backward compatible. So to continue supporting Gradle 4 we would need to support two versions of the plugin in parallel. Unfortunately, I don't have the resources for that and in the end Gradle 4 might not even work with the changes being done to the Vaadin platform due to the lack of proper BOM support. So the only solution I could think of is the require Gradle 5 now, which will cause some pain in the short term, but in the end will enable plugin to support any version of Gradle 5.x for a long time forward.

So yes, I understand your pain, but this is really necessary when thinking about the long term of the plugin.
