### ISSUE TITLE
Cannot use custom src directory when assembling client frontend

### ISSUE THREAD

**Issue by CodeMason** [devsoap/gradle-vaadin-flow#131]
Because `VaadinClientDependenciesExtension.WEBAPP_DIR` is static final, I cannot use a different location for my frontend when I want to build the ES5/6 dependencies.

Would is be possible to make this location configurable?

**Comment by johndevs** [comment]
`src/main/webapp` is used as a convention in many places and plugins, so just changing the constant to non-final would not be enough, at the same time we would need to change all places where the convention is used (for example the WAR plugin). 

Could you provide the use-case for why you would need to change the location of the webapp folder? Maybe we can solve that it in another way?

**Comment by dorkbox** [comment]
At work, we cannot change the source location (it's in `src`) and so our options are pretty limited. Additionally, we don't WAR any of the resources either, because vaadin is embedded using undertow as the servlet container.

**Comment by CodeMason** [comment]
At work, we cannot change the source location (it's in src) and so our options are pretty limited. Additionally, we don't WAR any of the resources either, because vaadin is embedded using undertow as the servlet container.

**Comment by CodeMason** [comment]
I should point out though, the plugin works for everything, except compiling ES5/6.

**Comment by apklein** [comment]
same problem here. i have Vaadin UI in a multimodule idea project. the frontend dir is generated at root of the build directory (module/build/frontend) and isnt seen thru http. the frontend dir is on: module/build/resources/main/META-INF/resources/frontend.

**Comment by apklein** [comment]
there is a temporal fix for this?

**Comment by CodeMason** [comment]
@johndevs, can you remove the `final` keyword from `VaadinClientDependenciesExtension.WEBAPP_DIR`? Doing so will not change the behavior in any way, but will allow us to set this to a different value as needed.

**Comment by CodeMason** [comment]
@johndevs I forgot to mention -- I don't use the `WAR` plugin or any other plugin where this is used when we build our project, so this wouldn't impact anything on your end, but would allow us to at least build the ES5/6 files.

**Comment by johndevs** [comment]
I've been planning to fix this in a bit different way, to make it a property of the assemble task where it is mainly used.

So to configure it in *build.gradle* it would look like this:
```
vaadinAssembleClient {
    webappDir 'src'
}
```
I'll try to get this in into the next RC version.

One caveat will be that if you make the `src` directory the  `webapp` directory is that you will get all your source files, tests, etc. also included in your artifact. Usually that is not what you want.

**Comment by dorkbox** [comment]
That looks perfect.

> One caveat will be that if you make the src directory the webapp directory is that you will get all your source files, tests, etc. also included in your artifact. Usually that is not what you want.

Good to know and not a problem at all.
