### ISSUE TITLE
Documention for initial project setup

### ISSUE THREAD

**Issue by muksihs** [devsoap/gradle-vaadin-flow#139]
Please add to documentation to run "gradle wrapper --gradle-version XXX" in the project directory *before* creating the build.gradle file. Where XXX is the minimum version of Gradle the plugin requires.

This eliminates issues with various gradle versions installed in OS. 

This has to be done *before* creating the build.gradle file else the gradle wrapper command will fail with an error that the plugin for vaadin requires gradle 5+ and the wrapper will not be installed.

**Comment by muksihs** [comment]
It also doesn't help any that the latest Gradle for download is listed as 4.10.2 on the linked to page for installation of Gradle.

**Comment by johndevs** [comment]
Gradle 5 is now released so the gradle install page refers to the right version of Gradle. 
Also added a section about running the wrapper before creating the build.gradle file.
