### ISSUE TITLE
Memory leak when running gradle daemon (M5/6)

### ISSUE THREAD

**Issue by rsivan** [devsoap/gradle-vaadin-flow#152]
**Desktop (please complete the following information):**
- OS: Linux
- Gradle version 4.10.2
- Vaadin Plugin version 1.0.0.M6 (also M5)
 
**Describe the bug**
 
com.devsoap.vaadinflow.models.ProjectType objects are leaked when using the vaadin-flow gradle plugin. This behavior was observed with the gradle daemon enabled and building a vaadin flow application multiple times in succession. After about 5 builds the gradle daemon start to run out of memory. Capturing a heap dump of the JVM and analyzing it with MAT (Eclipse Memory Analaysis Tool) reveals that 1.5 GB of the heap was consumed by the “ProjectType” class. Builds where the gradle daemon is restarted every time or where the vaadin-flow plugin is not used do not run out of memory.
 
**To Reproduce**
 
1.      Set ‘org.gradle.daemon=true’ in ~/.gradle/gradle.properties to enable the gradle daemon
2.      Create a project that uses vaadin-flow plugin to build a war.
3.      Build the war multiple times (gradlew clean war)
4.      Over time ProjectType classes will consume more and more memory in the gradle daemon java process.
 
**Expected behavior**

The memory used for ProjectType objects should not be leaked in the gradle daemon java process.

**Comment by johndevs** [comment]
Thanks for the excellent bug report! I'll check it out.
