### ISSUE TITLE
Problems enabling production mode

### ISSUE THREAD

**Issue by steffen-harbich-itc** [devsoap/gradle-vaadin-flow#160]
- OS: Windows
 - Gradle version 5
 - Vaadin Plugin version 1.0.0.RC3

When creating a gradle project from scratch following the getting started guide in wiki, the CSS file is not properly loaded in the web app and therefor styles are not applied to the test label. This is not really a problem for me but maybe annoying for others. However, I tried to enable the production mode and came up with an exception:

> HTTP ERROR 503
> 
> Problem accessing /pmode/. Reason:
> 
>     Service Unavailable
> 
> Caused by:
> 
> org.eclipse.jetty.servlet.ServletHolder$1: java.lang.IllegalArgumentException: Failed to find the bundle manifest file 'frontend://vaadin-flow-bundle-manifest.json' in the servlet context for 'ES6' browsers. If you are running a dev-mode servlet container in maven e.g. `jetty:run` change it to `jetty:run-exploded`. If you are not compiling frontend resources, include the 'vaadin-maven-plugin' in your build script. Otherwise, you can skip this error either by disabling production mode, or by setting the servlet parameter 'original.frontend.resources=true'.
> 	at org.eclipse.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:570)
> 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:634)
> 	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:472)
> 	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:767)
> 	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:752)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.IllegalArgumentException: Failed to find the bundle manifest file 'frontend://vaadin-flow-bundle-manifest.json' in the servlet context for 'ES6' browsers. If you are running a dev-mode servlet container in maven e.g. `jetty:run` change it to `jetty:run-exploded`. If you are not compiling frontend resources, include the 'vaadin-maven-plugin' in your build script. Otherwise, you can skip this error either by disabling production mode, or by setting the servlet parameter 'original.frontend.resources=true'.
> 	at com.vaadin.flow.server.startup.BundleFilterInitializer.readBundleManifest(BundleFilterInitializer.java:77)
> 	at com.vaadin.flow.server.startup.BundleFilterInitializer.addBundleFilterForBrowser(BundleFilterInitializer.java:68)
> 	at com.vaadin.flow.server.startup.BundleFilterInitializer.serviceInit(BundleFilterInitializer.java:62)
> 	at com.vaadin.flow.server.VaadinService.lambda$init$0(VaadinService.java:249)
> 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
> 	at com.vaadin.flow.server.VaadinService.init(VaadinService.java:249)
> 	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:259)
> 	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:240)
> 	at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:77)
> 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:616)
> 	... 21 more

**To Reproduce**
Steps to reproduce the behavior: Start the attached gradle build with jetty:run and try accessing the application.
[pmode.zip](https://github.com/devsoap/gradle-vaadin-flow/files/2632954/pmode.zip)

**Expected behavior**
No error should appear when accessing the application and it should be working on IE11.

**Additional context**
I am trying to enable the production mode to be able to view my app on older browsers like IE11.

**Comment by johndevs** [comment]
Hi, I tested your attached application and by upgrading the plugin to RC4 it will work. This is something that was fixed recently.
