### ISSUE TITLE
Support of Java 11 -> update eclipse jetty plugin to 9.4.14.v20181114?

### ISSUE THREAD

**Issue by marcelbaumann** [devsoap/gradle-vaadin-flow#161]
It could be that currently, the configuration does not support Java 11. I get asm errors with the eclipse jetty plugin.

I tried the eclipe-jetty plugin version 9.4.14.v20181114 in another vaadin project by modifying the maven configuration file of a start project taken from the vaadin home page and vaadin version 11.0.2 and 11.0.3, both worked.

Could you update the plugin dependencies to use the newer eclipse-jetty plugin?

**Comment by johndevs** [comment]
Actually, this was done in #162 but I'll keep this open until you can verify it working with 1.0.0.RC4 when it is released.

**Comment by johndevs** [comment]
This should now be fixed, please try RC4 and re-open if you are still seeing this issue.
