### ISSUE TITLE
bundleExcludes has no effect

### ISSUE THREAD

**Issue by brp-oskar** [devsoap/gradle-vaadin-flow#174]
**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - JDK version: 8
 - Gradle version: 5.0
 - Vaadin Plugin version: 1.0.0.RC4

**Describe the bug**
The issue #113 was closed with a PR but the code changes did not have any effect. The problem is that the property is declared wrong. Now it is
```
private final Property<List<String>> bundleExcludes = project.objects.property(String)
```
but it should be
```
private final ListProperty<String> bundleExcludes = project.objects.listProperty(String).empty()
```
The test in `ClientDependenciesTest.groovy` is also wrong because it only calls the getter `bundleExcludes ['https://www.gstatic.com/charts/loader.js']`. It should be `bundleExcludes = ['https://www.gstatic.com/charts/loader.js']` or `setBundleExcludes ['https://www.gstatic.com/charts/loader.js']`

**To Reproduce**
Run the test `ClientDependenciesTest.'exclude specific imports from bundle'` with the change `bundleExcludes = ...`.
It will result in a runtime error.

**Expected behavior**
The same as in #113 

**Additional context**
I have tried to make the test work with my changes but I can't understand why it fails. It stops at `Transpiling...` because the previous step `yarnBundleRunner.polymerBundle(...)` fails to create the `vaadin-flow-bundle-manifest.json` file. I have tried to change the arguments to `polymer-bundler` but can't make it create the file.

Here are my changes:
```
// ClientDependenciesTest.groovy
void 'exclude specific imports from bundle'() {
    setup:
        buildFile << '''
               vaadinTranspileDependencies {
                   bundleExcludes = ['https://www.gstatic.com/charts/loader.js']
               }
               vaadinClientDependencies {
                   yarn '@google-web-components/google-chart:3.0.0'
               }

               vaadin.productionMode = true
               vaadin.autoconfigure()
        '''.stripIndent()
```
and
```
// TranspileDependenciesTask.groovy
private final ListProperty<String> bundleExcludes = project.objects.listProperty(String).empty()
```

**Comment by johndevs** [comment]
Looks like the order how the ``--exclude`` parameters are passed to ``polymer-bundler`` command is relevant, they need to be passed before any other parameters. Thanks for also noticing the wrong property type, totally missed that :+1:
