### ISSUE TITLE
Spring Boot support

### ISSUE THREAD

**Issue by johndevs** [devsoap/gradle-vaadin-flow#18]
Detect the Spring Boot gradle plugin and configure the outputs for running in a JAR or WAR depending on how the spring boot plugin is configured

**Comment by YeTingGe** [comment]
As I'm also using spring-boot along with Vaadin, and prefer Gradle rather than Maven, hopefully, this tool can support spring boot.
I spend two days to start my project by Gradle in production mode but failed.
Frankly speaking, Vaadin is changing too fast...

**Comment by torstenwerner** [comment]
Gradle is officially supported by Vaadin 11 https://vaadin.com/blog/vaadin-11-is-now-available-with-gradle-support-and-new-components but I haven't tested it yet.
