### ISSUE TITLE
Building production mode on Windows fails

### ISSUE THREAD

**Issue by tohkawaics** [devsoap/gradle-vaadin-flow#193]
**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - JDK version: 8
 - Gradle version: 5.0
 - Vaadin Plugin version: 1.0.0.RC7

**Describe the bug**
Building beverage-starter-flow-gradle project with production mode enabled fails with the following output:

```
> Configure project :
Using Gradle Vaadin Flow Plugin 1.0.0-RC7
Allow Vaadin to gather usage statistics by setting vaadin.submitStatistics=true (hide this message by setting it to false)

> Task :vaadinTranspileDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vaadinTranspileDependencies'.
> Process 'command 'D:\Projects\beverage-starter-flow-gradle\.gradle\yarn\yarn-v1.12.3\yarn.cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 47s
7 actionable tasks: 5 executed, 2 up-to-date
```

 This occurs on Windows only. On Ubuntu Linux, there's no problem.

 When commenting out the following lines of build.gradle, the problem does not occur.

```
//// In production mode we want to exclude the Material styles imported from all vaadin components
//vaadinTranspileDependencies {
//    importExcludes = [
//        '.*/theme/material/.*',
//        '.*/vaadin-material-styles/.*'
//    ]
//}
//
//// We don't want the Material style Maven dependencies in our project either
//configurations.all {
//    exclude group: 'com.vaadin', module: 'vaadin-material-theme'
//    exclude group: 'org.webjars.bowergithub.vaadin', module: 'vaadin-material-styles'
//}
```

**To Reproduce**
1. clone example repositlry
2. uncomment ``productionMode = true`` in build.gradle
2. Run Gradle task 'jettyRun'
4. See the error above.

**Comment by brp-oskar** [comment]
You will get a better error message if you run gradle with `--info` flag. It will say that some material file is not found.

The regex that is used inside `importExcludes` only works with Linux path separators. Try with these lines instead. It supports both Linux and WIndows path separators.
```
vaadinTranspileDependencies {
    importExcludes = [
        /.*[\\\/]theme[\\\/]material[\\\/].*/,
        /.*[\\\/]vaadin-material-styles[\\\/].*/,
    ]
}
```
