### ISSUE TITLE
Styles folder

### ISSUE THREAD

**Issue by alabotski** [devsoap/gradle-vaadin-flow#195]
In webapp I have such structure

<img width="339" alt="image" src="https://user-images.githubusercontent.com/439337/52412810-c0a6c180-2ad7-11e9-825f-d26b610d3f1e.png">

When I build in production mode 

<img width="249" alt="image" src="https://user-images.githubusercontent.com/439337/52412848-da480900-2ad7-11e9-82cc-b54411bd4836.png">

Why folder styles always empty?

**Comment by johndevs** [comment]
In production mode the styles and templates are not copied into _build/frontend_, they are instead copied into the transpiled frontend directories **frontend-es5** and **frontend-es6**.
