### ISSUE TITLE
Support Vaadin Flow projects in Kotlin

### ISSUE THREAD

**Issue by johndevs** [devsoap/gradle-vaadin-flow#20]
To support Kotlin we at least need Kotlin templates for the various creation tasks.

**Comment by joelhandwell** [comment]
Will this milestone also aims to integrate with [vaadin-on-kotlin](https://github.com/mvysny/vaadin-on-kotlin) ?

**Comment by johndevs** [comment]
The templates should be generic and not depend on third party libraries so they won't generate directly VoK DSL but instead native Kotlin. 

But the plugin should work just fine with VoK as well just as the Vaadin 8 plugin also works today. I'm also sure once M6 is out then we can improve the support for VoK as well.

**Comment by joelhandwell** [comment]
Do you consider to add something like ```--lang``` option for  ```vaadinCreateProject``` task so that generated skeleton code can be chosen to be kotlin?

**Comment by johndevs** [comment]
I was thinking that ``vaadinCreateProject`` would automatically select Kotlin skeletons when the official kotlin plugin is applied. This is how it has been implemented in the Vaadin 8 plugin.

So it would be enough to have this in your build.gradle to create Kotlin projects:
```
plugins {
    id "org.jetbrains.kotlin.jvm" version "1.2.51"
    id "com.devsoap.vaadin-flow" version "1.0.0.M6"
}
```
This way you don't have to know about extra options, the plugin would be smart enough to select the correct skeleton for the correct language.

**Comment by joelhandwell** [comment]
@johndevs Thank you for the hard work. Will you release M5 any days soon?

**Comment by johndevs** [comment]
@joelhandwell I'm pretty sure something might happen on the weekend ;)
