### ISSUE TITLE
Include project dependencies when unpacking webjars

### ISSUE THREAD

**Issue by brp-oskar** [devsoap/gradle-vaadin-flow#202]
**Is your feature request related to a problem? Please describe.**
We would like to include project dependencies when unpacking webjars. Currently project dependencies are excluded in [WebJarHelper.groovy](https://github.com/devsoap/gradle-vaadin-flow/blob/05e676efcf6dcaae2c659cad66be3b109276a85e/src/main/groovy/com/devsoap/vaadinflow/util/WebJarHelper.groovy#L78).

Our `build.gradle` looks like this:
```
dependencies {
    // Contains templates in folder "src/main/resources/META-INF/resources/frontend/templates"
    compile project(':base')
    // Webjar for a client side component
    compile project(path: ":webcomponent", configuration: "calendarWebjar")
}
```

**Describe the solution you'd like**
Either remove the exclude or add a property that enables/disables the exclude.

**Describe alternatives you've considered**
I have tested a build with and without the exclude of project dependencies. I didn't see any side effects with my project setup. Do you know why the exclude is there?

**Comment by tohkawaics** [comment]
We need this feature too.
