### ISSUE TITLE
Gretty buildProduct + ./run.sh fails

### ISSUE THREAD

**Issue by aollag09** [devsoap/gradle-vaadin-flow#209]
**Desktop (please complete the following information):**
 - OS: [e.g. Unix]
 - JDK version: 1.8.0_191
 - Gradle version: 5.2.1
 - Vaadin Plugin version: 1.0.0.RC8

**Describe the bug**
Hello, 
I've set up a basic vaadin flow gradle project using the plugin.
Everything works fine when I launch the appRun task. 
But when I launch Gretty buildProduct task + ./run.sh, it fails.

My application looks like this :( 
![image](https://user-images.githubusercontent.com/1586329/53883025-32f7bc80-4018-11e9-91c4-c9301246f063.png)

**To Reproduce**
1. Setup default project 
2. Run Gradle task appRun : works fine !
3. Run Gradle task buildProduct : works fine !
4. Run build/output/myapp/start.sh or run.sh : fails :( 
4. See error '....'

**Expected behavior**
I would like my application to run exaclty the same with : 
- gradle appRun
- gradle buildProduct + ./start.sh

Thanks for your help :) !

**Comment by johndevs** [comment]
Currently Gretty **buildProduct** only works when you build the project as a WAR. 

So add the following to your build.gradle and it should work:
```
plugins {
    id 'war'
}
```

I'll improve this for 1.1 to also work without WAR packaging.

**Comment by aollag09** [comment]
Hello !
Thanks for the answer, I confirm this is working fine :) !
