### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by PabloIT** [devsoap/gradle-vaadin-flow#217]
In a large project, when productionMode = true, an error occurs:

![image](https://user-images.githubusercontent.com/26419773/54353411-4c21ee00-4654-11e9-91dc-ba0f3cd69f22.png)

The solution may be to increase or to set the parameter for the node: --max-old-space-size

Example of the yarn.cmd file:
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe" "--max-old-space-size=8192" "%~dp0\node_modules\yarn\bin\yarn.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node "--max-old-space-size=8192" "%~dp0\node_modules\yarn\bin\yarn.js" %*
)
```

**Comment by johndevs** [comment]
Could you try adding the following to your build.gradle and see if it works?

```
vaadinTranspileDependencies.yarnRunner.environment.put('NODE_OPTIONS', '--max-old-space-size=8192')
```

**Comment by PabloIT** [comment]
I confirm, the given solution works well. Thanks.
