### ISSUE TITLE
Production mode Java Script

### ISSUE THREAD

**Issue by alabotski** [devsoap/gradle-vaadin-flow#226]
1. Add dependencies
```
    implementation 'org.webjars.bower:jquery:3.3.1'
```
2. Import JS
```
<link rel="import" href="../../../bower_components/3.3.1/dist/jquery.min.js">
```
or
```
@JavaScript("frontend://bower_components/3.3.1/dist/jquery.min.js")
```

The problem is that in development mode. The right way
```
frontend://bower_components/3.3.1/jquery/dist/jquery.min.js
```

But in production mode
```
frontend://bower_components/3.3.1/dist/jquery.min.js
```

**Comment by alabotski** [comment]
The second problem when I add JS such
```
<link rel="import" href="../../bower_components/d3/5.7.0/d3.min.js">
```

I have error
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/439337/55165626-ce470200-517e-11e9-862c-1509a51f5787.png">

I must explicitly specify the script tag.
With `@JavaScript` all work well.

**Comment by johndevs** [comment]
Looks like the jquery webjar is not unpacked correctly. It should be unpacked to ``../build/frontend/bower_components/jquery/dist/jquery.min.js``.
