### ISSUE TITLE
Defining Fragments

### ISSUE THREAD

**Issue by alabotski** [devsoap/gradle-vaadin-flow#244]
Does the plugin support Defining Fragments?

https://vaadin.com/docs/v13/flow/production/tutorial-production-mode-customising.html

**Comment by johndevs** [comment]
No, no support for those yet.

**Comment by johndevs** [comment]
Just to point out that currently fragments are not really recommended due to issues described in https://github.com/vaadin/flow/issues/3588. 

That means it is not likely this will be implemented in a while (unless somebody creates a PR).

**Comment by johndevs** [comment]
Closing this as this refers to the old fragments implementation that will not be supported.
