### ISSUE TITLE
Changing lumo variables doesn't work

### ISSUE THREAD

**Issue by ssindelar** [devsoap/gradle-vaadin-flow#246]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - JDK version: jdk 8 and 11
 - Gradle version: 5.3
 - Vaadin Plugin version: 1.1.1

**Describe the bug**
Changing the lumo variables doesn't work in production mode.
see: https://cdn.vaadin.com/vaadin-lumo-styles/1.4.1/demo/customization.html

**To Reproduce**
1. Take any vaadin flow project
2. Set a lumo varable e.g.:
```
<custom-style>
    <style>
    	html {
    		--lumo-primary-color: #FF0000;
    	}	
    </style>
</custom-style>
```
3. Start with productionmode = false -> it works
4. Start with productionmode = true -> default color

**Expected behavior**
Production mode also changes color

Compiling the same project using maven works.

**Comment by johndevs** [comment]
That is interesting.

For example the Beverage Starter Flow example uses Lumo variables it it is working (https://github.com/devsoap/examples/blob/master/beverage-starter-flow-gradle/src/main/webapp/frontend/styles/shared-styles.html)

**Comment by ssindelar** [comment]
Thats really interessting because I gave your example a try and it worked. Than I tried it again in our application and it didn't work.

I noticed an other strange thing. In our application it workes in Firefox but not in IE, Edge and Chrome.

Currently I don't have the time to investigate it further, but I will as soon as possible.

**Comment by johndevs** [comment]
Closing this as this has been open for some time now. Re-open if you find a way to reproduce this.
