### ISSUE TITLE
documentation around location of templates 

### ISSUE THREAD

**Issue by bsutton** [devsoap/gradle-vaadin-flow#258]
The new vaadin 14 migration guide states that the frontend directory should be stored in the root of the project.

The gradle vaadin flow project states that templates should be stored under /src/main/webapps/frontend/templates.

Can the documentation be updated to note and clarify the differences.

**Comment by johndevs** [comment]
Project structure information for V14 is now available at http://docs.devsoap.com/vaadin_flow_gradle_plugin/project_structure.html
