### ISSUE TITLE
build fail for java library

### ISSUE THREAD

**Issue by mdre** [devsoap/gradle-vaadin-flow#259]
**Desktop (please complete the following information):**
 - OS: Ubuntu
 - JDK version: 11 
 - Gradle version: 5.5
 - Vaadin Plugin version: 1.2

**Describe the bug**
The build process fail with this error: 

```
> gradle build

> Configure project :
22/07/2019 12:00:36
---------------------------------------------------------------
Using Gradle Vaadin Flow Plugin 1.2.0
Allow Vaadin to gather usage statistics by setting vaadin.submitStatistics=true (hide this message by setting it to false)

> Task :vaadinInstallYarnDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vaadinInstallYarnDependencies'.
> Process 'command '/home/mdre/Proyectos/WEB/QuienCotizaProject/QCVaadinFlowCC/.gradle/yarn/yarn-v1.12.3/bin/yarn'' finished with non-zero exit value 139

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
5 actionable tasks: 1 executed, 4 up-to-date
```

The plugin work well combined with the 'war' plugin, but fail for 'java' plugin. 
It was working well but now it fail.

[test.zip](https://github.com/devsoap/gradle-vaadin-flow/files/3418766/test.zip)

**To Reproduce**
1. Setup project: uncompress the attached file
2. Run Gradle task 'build'
4. See error '....'

**Expected behavior**
It must build a .jar file in the lib diretory

**Comment by mdre** [comment]
Version 1.1.2 work well.

**Comment by integrigy** [comment]
OS: Ubuntu
JDK version: 11.0.4
Gradle version: 5.6.2
Vaadin Plugin version: 1.2
Vaadin: 14.0.3

I am encountering the same error.  With --info and --debug see it is failing on the following command -

11:52:25.130 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command '/home/bob/work/vaadintest/.gradle/yarn/yarn-v1.12.3/bin/yarn''. Working directory: /home/bob/work/vaadintest/build/frontend Command: /home/bob/work/vaadintest/.gradle/yarn/yarn-v1.12.3/bin/yarn --prefer-offline --cwd /home/bob/work/vaadintest/build/frontend init -y
11:52:25.219 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
11:52:25.219 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/home/bob/work/vaadintest/.gradle/yarn/yarn-v1.12.3/bin/yarn'' finished with exit value 139 (state: FAILED)

The following comands executed are successful when executed outside of gradle -
cd /home/bob/work/vaadintest/build/frontend 
/home/bob/work/vaadintest/.gradle/yarn/yarn-v1.12.3/bin/yarn --prefer-offline --cwd /home/bob/work/vaadintest/build/frontend init -y

Not sure how to further debug why yarn is returning exit code 139.

**Comment by johndevs** [comment]
Hi, I tested the Zip file and updated the plugin version to ``1.3.beta5`` and got the following;

```
> Task :build
***************************************************************
SISTEMA: build
VERSION: 0.2.0.3
***************************************************************

BUILD SUCCESSFUL in 11s
12 actionable tasks: 7 executed, 5 up-to-date
```
So looks like it works with the latest plugin. Please update to the latest version and re-open if you still are having issues.
