### ISSUE TITLE
Consider releasing 1.2.1

### ISSUE THREAD

**Issue by tbalzer** [devsoap/gradle-vaadin-flow#270]
We are facing some issues related to vaadin 14 that seem to have been addressed (based on commit logs) since the latest release 1.2
Is there any timeline to get a fixup release 1.2.1 out?

**Comment by johndevs** [comment]
Any specific issue? 

The next feature release from master branch (1.3) will not happen for a while, but if there are bugs that could be fixed by backporting fixes from master branch into 1.2.x I am happy to do so and release a 1.2.1 to fix them up.

**Comment by tbalzer** [comment]
We have issues using gradle-vaadin-plugin with Vaadin 14 in production mode (stats.json is missing). 
We are using Vaadin in an embedded jetty inside a larger non-web application and are migrating form 8.x (which required no gradle plugins) to 14.x.

Sounded similar to https://github.com/vaadin/flow/issues/6277 which refers to open issues with the gradle-vaadin-plugin. Some commits in master seemed to match the problem space and are a part of the larger issues #240 I guess?
Maybe our usecase is just not supported until 1.3 and we should use Vaadin 13 until then?

**Comment by johndevs** [comment]
The stats.json file is part of the polymer 3 support being worked on in #240. 
Right now you can use Vaadin 14 but you need to run it in compatibility mode (i.e set vaadin.compatibilityMode = true). It essentially the same as Vaadin 13 but with all Vaadin 14 features except it doesn't support Polymer 3 components.

**Comment by AustinShalit** [comment]
There is no `compatibilityMode` property in version 1.2 of the plugin. This is the error that Jetty reports when attempting to use Vaadin 14:
```
org.eclipse.jetty.servlet.ServletHolder$1: java.lang.IllegalStateException: Unable to determine mode of operation. To use npm mode, ensure 'flow-build-info.json' exists on the classpath.
```
@johndevs Please advise

**Comment by Shridhad** [comment]
@AustinShalit You can set the `compatibilityMode` to true using `@WebInitParam` on your web servlet class. Or configure it in `web.xml` just like all other [Vaadin Properties](https://vaadin.com/docs/v14/flow/advanced/tutorial-all-vaadin-properties.html)

**Comment by johndevs** [comment]
The plugin will automatically run in compatibility mode if you build a Vaadin 14 project. You don't need to set a compatibility mode flag.

Have you set ``vaadin.version=14.0.0``?

As a rule, do not pay any attention to any error messages you are getting from ``com.vaadin`` classes. The Vaadin guys mostly care about Maven and all error messages have been crafted for Maven users only. It sucks but they really don't seem to care about changing those.

I haven't tested the latest maintenance releases though, it is fully possible that they have broken the support as well. It has tended to happen more than once.

**Comment by AustinShalit** [comment]
I still did not figure out how to embed Jetty into the produced Jar so I decided to go with using Gretty's `buildProduct` instead.  When implementing that I encountered issue #282.

**Comment by johndevs** [comment]
Closing this as there will not be a 1.2 release, next release is 1.3.
