### ISSUE TITLE
Remove hard link to https://plugins.gradle.org/m2 for disconnected environments

### ISSUE THREAD

**Issue by antioh** [devsoap/gradle-vaadin-flow#297]
**Desktop (please complete the following information):**
 - OS:  Windows
 - JDK version: 8 
 - Gradle version: 5.6.3
 - Vaadin Plugin version: 1.2

Hard link to plugins.gradle.org doesn't allow to use proxy repository( Nexus ).
Artifacts, resolved through 
consider use in VaadinFlowPluginAction.groovy gradle override property, something like this:
....
            repositories.maven { repository ->
                repository.name = 'Gradle Plugin Portal'
                repository.url = (System.getProperty('org.gradle.internal.plugins.portal.url.override') )?: 'https://plugins.gradle.org/m2/'
            }
thanks

**Comment by johndevs** [comment]
Looks like that property is exposed via the ``BaseRepositoryFactory.PLUGIN_PORTAL_OVERRIDE_URL_PROPERTY`` .

Good find, I'll add it :+1:
