### ISSUE TITLE
Fail to setup npm

### ISSUE THREAD

**Issue by vinz486** [devsoap/gradle-vaadin-flow#299]
**Desktop (please complete the following information):**
 - OS: Windows
 - JDK version: 8 
 - Gradle version: 5.6.2
 - Vaadin Plugin version: 1.2

**Describe the bug**
On a fresh project, running the "npmInstall" task give errors

**To Reproduce**
1. Setup project  with Spring 2.2.0.RELEASE and Vaadin 14.0.5
2. Run Gradle task npmInstall'
4. See error:
`17:11:40: Executing task 'npmInstall'...

> Configure project :
Using Gradle Vaadin Flow Plugin 1.2.0
Allow Vaadin to gather usage statistics by setting vaadin.submitStatistics=true (hide this message by setting it to false)

> Task :nodeSetup UP-TO-DATE
> Task :npmSetup UP-TO-DATE
> Task :npmInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':npmInstall'.
> File 'C:\Users\TarriconeV\IdeaProjects\dash\build\frontend\package-lock.json' specified for property '$2' does not exist.
> File 'C:\Users\TarriconeV\IdeaProjects\dash\build\frontend\package.json' specified for property '$1' does not exist.
`

**Expected behavior**
node and npm installed locally

**Additional context**
This is a fresh project on a fresh workstation.

**Comment by johndevs** [comment]
Hi,

Could you try the latest beta release of 1.3? The latest version in 1.3.beta5

**Comment by vinz486** [comment]
Done. Same errors but now I have also:

"The project will be compiled for Vaadin 13 (Flow 1) compatibility mode.  Running in NPM mode is only available for PRO subscribers."

And I'm not a pro subscriber.
