### ISSUE TITLE
Execution failed for task ':jettyRun' 

### ISSUE THREAD

**Issue by michaelcordero** [devsoap/gradle-vaadin-flow#301]
**Desktop (please complete the following information):**
 - OS: Mac OS X
 - JDK version: 11
 - Gradle version: 5.6.2
 - Vaadin Plugin version: 1.3.beta5

**Describe the bug**
The devsoap license plugin has transitive dependencies issues.

**To Reproduce**
1. Try to create a brand new project using 1.3 Beta 5. 
2. On the website devsoap, it lists:
`id "com.devsoap.vaadin-flow" version "1.3"`, but this will not work so you have to change it to:
`id "com.devsoap.vaadin-flow" version "1.3.beta5"`. 
3. Once you can actually build the project, you can also add the Gretty plugin: `id "org.gretty" version '2.3.1'`. If you try the `appRun` task or even the `jettyRun` like the website instructions say, you will see the same transitive dependencies error: 
```
Execution failed for task ':jettyRun'.
> Could not resolve all dependencies for configuration ':compileOnly'.
   > Could not resolve com.fasterxml.jackson.core:jackson-databind:2.9.9.3.
     Required by:
         project : > com.devsoap:devsoap-license-plugin:1.0.3 > com.auth0:java-jwt:3.8.2
      >
 > Could not resolve commons-codec:commons-codec:1.12.
     Required by:
         project : > com.devsoap:devsoap-license-plugin:1.0.3 > com.auth0:java-jwt:3.8.2
```

**Expected behavior**
I expected the `jettyRun` or `appRun` with no failures.

**Screenshots**

<img width="1668" alt="Screen Shot 2019-10-31 at 2 20 25 AM" src="https://user-images.githubusercontent.com/8487086/67926829-11d67400-fb85-11e9-9dd6-a833b489fa1b.png">

**Additional context**

**Comment by johndevs** [comment]
Hi,

Since you are running in ``--offline`` mode you will need to have downloaded all the dependencies previously into your gradle cache. 

Try toggling the ![Selection_090](https://user-images.githubusercontent.com/1967917/67927249-cc379c80-fbc0-11e9-8d86-c499edc20d7f.png) -button off so you are in online mode. It should start downloading your dependencies.

**Comment by michaelcordero** [comment]
@johndevs Ok that worked. Thanks! One more question, how do I get IntelliJ's debugger to work with gretty/appRun/jettyRun?

**Comment by johndevs** [comment]
You will need to run the application with the jettyRunDebug or appRunDebug Gradle tasks and attach a remote debugger. @mvysny has made a great video about that here https://youtu.be/M0Q7D03bYXc?t=341.

The application will be running on port 8080 once you have successfully attached the remote debugger. You usually get that exception if you are trying to access the application via the debugger port (5005).

**Comment by michaelcordero** [comment]
Hi John, ok the suggestions made in the video worked, but for anyone that comes across the issue, it might be good to post the link with the actual instructions [here](https://github.com/akhikhl/gretty/issues/36). Also, I think it would be helpful to mention this issue on your [website](https://docs.devsoap.com/vaadin_flow_gradle_plugin_tasks/creating_a_new_project_java_2.html). Not having debug mode made me seriously consider just trying an entirely different framework.

**Comment by johndevs** [comment]
@michaelcordero You are right, the documentation is lacking in this regard. I think everybody is going to hit this issue when starting out with the plugin so it is important that this would be documented as good as possible.
