### ISSUE TITLE
Question: Release for production build

### ISSUE THREAD

**Issue by brp-oskar** [devsoap/gradle-vaadin-flow#69]
Hi!
Is there a plan for a release with build for production mode? The wiki say "Comming soon" but there seems to be commits after the M2 release that is about production mode.

**Comment by brp-oskar** [comment]
There is a M3 release listed at https://plugins.gradle.org/plugin/com.devsoap.vaadin-flow but it is not tagged in this repo.

**Comment by johndevs** [comment]
Hi, thanks for noticing that the tag is missing, I'll add asap.

**Comment by johndevs** [comment]
Release tagged, I'll mark this as a documentation task to fill in the missing wiki page.

**Comment by johndevs** [comment]
Wiki page updated https://github.com/devsoap/gradle-vaadin-flow/wiki/Building-for-production
