### ISSUE TITLE
Node modules cleared each build?

### ISSUE THREAD

**Issue by Polish-Civil** [devsoap/gradle-vaadin-flow#76]
Why node_modules directory under build/ gets cleared each time i build the application? Is this necessary? Building takes ages doing so

**Comment by johndevs** [comment]
It should only get removed when running the ``clean`` task so if you for example are running ``gradle clean build`` it will remove it every time.

**Comment by Polish-Civil** [comment]
Um im running appRun from gretty, im really sorry if they depend on the clean but i don't think so?

![image](https://user-images.githubusercontent.com/10587799/42682917-dd31e9b0-8659-11e8-8c89-fbe32183eac7.png)

**Comment by Polish-Civil** [comment]
Im executing appRun from gretty, basically the task 'vaadinInstallDependencies' is executed very often, i guess it might be gretty's behaviour.

Is there possibility to move npm bower etc to the gradle cache system?

**Comment by johndevs** [comment]
> Is there possibility to move npm bower etc to the gradle cache system?

This would have been my hope as well but unfortunately it is not possible with the current version of Gradle due to Gradle not caching the symlinks in node_modules. I attempted this already in #56 .

**Comment by johndevs** [comment]
Added a Yarn cache in (#80) to prevent the downloads as well as removed the removal of node_modules.
