### ISSUE TITLE
Running unlinked binaries as yarn scripts does not work on Windows

### ISSUE THREAD

**Issue by brp-benjamin** [devsoap/gradle-vaadin-flow#94]
Commit a33d772bae13d8a983630fbdd82e43cb60a59577 runs yarn without linking binaries. Included in this change is a yarn script for bower that points to "node_modules/bower/bin/bower".

This does not work in a Windows environment and will result in a command not found error leading to the build failing halfway through.

**Comment by johndevs** [comment]
Fixed in M4.1
