### ISSUE TITLE
Directory 'build\webapp-gen\frontend\styles' does not exist

### ISSUE THREAD

**Issue by steffen-harbich-itc** [devsoap/gradle-vaadin-flow#97]
When running my spring boot vaadin flow application with the gradle plugin in production mode, I get the following error:

A problem was found with the configuration of task ':ui-vaadin-10:vaadinTranspileDependencies'.
> Directory '[path to my project root]\ui-vaadin-10\build\webapp-gen\frontend\styles' specified for property 'webappGenFrontendStylesDir' does not exist.

Creating this folder manually solves the problem.

**Comment by bsideup** [comment]
@johndevs if it helps, we observe the same issue. 
Steps to reproduce: move Vaadin flow app into a sub-module
